---

- name: Install debian specific package_facts dependency
  become: true
  when: ansible_distribution == "Debian"
  ansible.builtin.package:
    name: python-apt-common
    state: present

- name: Get davinci resolve version
  become: true
  become_user: "{{ user }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ user_path }}"
  ansible.builtin.command:
    cmd: resolve -v
  register: present_dresolve_version
  changed_when: false

- name: Set davinci resolve version
  ansible.builtin.set_fact:
    dresolve_version_version: "{{ present_dresolve_version.stdout_lines[-1] }}"

# Was intended to generate user config but doesn't work due to license check
- name: Launch davinci resolve headless
  become: true
  become_user: "{{ user }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ user_path }}"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      timeout 3s resolve
    executable: /bin/bash
  register: dresolve_hedless_launch
  changed_when: false
  failed_when: dresolve_hedless_launch.rc not in [0, 124]

# - name: Install xml module requirements
#   ansible.builtin.package:
#     name: python3-lxml

# INFO config.user.xml gets created after license check - so this doens't work with studio version
# file copy won't work due to unique DbId
# - name: Write user config
#   become: true
#   become_user: "{{ user }}"
#   loop: "{{ dresolve_user_settings | dict2items }}"
#   community.general.xml:
#     path: "{{ user_home }}/.local/share/DaVinciResolve/configs/config.user.xml"
#     xpath: "/SM_UserPrefs/{{ item.key }}"
#     value: "{{ item.value | string }}"

- name: Setup dresolve dev env
  when: dresolve_pipeline_dev
  ansible.builtin.include_tasks:
    file: development_setup.yml

...
